Inclusão do provedor SystemPro
ACBrNet/ACBr.Net.NFSe pull request #183
Opened 2021-08-18 20:11 UTC by transis2

2021-08-18 20:24 UTC, rftd requested changes

2021-08-18 20:24 UTC, rftd commented on src/ACBr.Net.NFSe/Providers/SystemPro/ProviderSystemPro.cs
> +            Name = "ISSe";
O nome do provedor esta errado.

2021-08-19 12:16 UTC, transis2 commented on src/ACBr.Net.NFSe/Providers/SystemPro/ProviderSystemPro.cs
> +            Name = "ISSe";
Ainda tem outros erros tb, mas eu só gerei um PR inicial com o esqueleto.
Quando der tempo eu vou terminar de implementar esse provedor.

2021-08-19 12:30 UTC, rftd approved these changes

2021-08-19 12:30 UTC, merged