Correções para SystemPro
ACBrNet/ACBr.Net.NFSe pull request #185
Opened 2021-08-20 20:13 UTC by transis2

2021-08-23 00:34 UTC, rftd commented on src/ACBr.Net.NFSe/Providers/SystemPro/SystemProServiceClient.cs
> +            //envelope.Append(soapHeader.IsEmpty() ? "<SOAP-ENV:Header/>" : $"<SOAP-ENV:Header>{soapHeader}</SOAP-ENV:Header>");
Não entendi o motivo de reescrita do metodo ?
O provedor esta recusando o header do soap mesmo sendo do padrão ter ele ?

2021-08-23 14:35 UTC, transis2 commented on src/ACBr.Net.NFSe/Providers/SystemPro/SystemProServiceClient.cs
> +            //envelope.Append(soapHeader.IsEmpty() ? "<SOAP-ENV:Header/>" : $"<SOAP-ENV:Header>{soapHeader}</SOAP-ENV:Header>");
Eu tentei re-escrever para ver se resolvia o erro abaixo e tb eu vi que eles fizeram assim no ACBR

![image](https://user-images.githubusercontent.com/4941173/130465938-59a256b0-dd52-4320-ae5b-c8fb3960132b.png)

A solicitação HTTP não está autorizada no esquema de autenticação de cliente 'Anonymous'. O cabeçalho de autenticação recebido do servidor foi 'Basic realm="certificate"'.

2021-08-23 23:54 UTC, rftd commented on src/ACBr.Net.NFSe/Providers/SystemPro/SystemProServiceClient.cs
> +            //envelope.Append(soapHeader.IsEmpty() ? "<SOAP-ENV:Header/>" : $"<SOAP-ENV:Header>{soapHeader}</SOAP-ENV:Header>");
Então pelo erro citado ele espera que o certificado seja passado na conexão e você não esta passando.

2021-08-24 12:02 UTC, transis2 commented on src/ACBr.Net.NFSe/Providers/SystemPro/SystemProServiceClient.cs
> +            //envelope.Append(soapHeader.IsEmpty() ? "<SOAP-ENV:Header/>" : $"<SOAP-ENV:Header>{soapHeader}</SOAP-ENV:Header>");
É diferente a forma de passar o certificado dos outros provedores ? Pq eu já estou carregando o certificado no construtor do SystemProServiceClient

2021-08-24 16:43 UTC, rftd commented on src/ACBr.Net.NFSe/Providers/SystemPro/SystemProServiceClient.cs
> +            //envelope.Append(soapHeader.IsEmpty() ? "<SOAP-ENV:Header/>" : $"<SOAP-ENV:Header>{soapHeader}</SOAP-ENV:Header>");
Não é exatamente assim, depois eu do uma olhada nos fontes do ACBr para ver se tem mais alguma bagunça neste provedor

2021-08-26 12:44 UTC, Transis-Felipe commented on src/ACBr.Net.NFSe/Providers/SystemPro/SystemProServiceClient.cs
> +            //envelope.Append(soapHeader.IsEmpty() ? "<SOAP-ENV:Header/>" : $"<SOAP-ENV:Header>{soapHeader}</SOAP-ENV:Header>");
Eu verifiquei no ACBr que a consulta e a substituição tem uma regra diferente, para esse provedor, dentro do ACBrNFSeWebServices.pas

Também estou procurando lá no projeto...

Vixi, tem diferenças também no XML dos dados. Mais um provedor que está de parabéns!

![image](https://user-images.githubusercontent.com/4941173/130965781-a54dbece-c1ec-4377-bf5c-00eb88bca354.png)

2021-08-26 20:50 UTC, Transis-Felipe commented
Faz um merge nessas últimas alterações, por favor.
Quero começar a fazer outro provedor.

2021-08-26 21:03 UTC, rftd requested changes

2021-08-26 21:03 UTC, rftd commented on src/ACBr.Net.NFSe/Providers/NFSeServiceClient.cs
> +            {
Se não vai tratar não precisa de um catch que so tenha throw;

2021-08-26 21:07 UTC, Transis-Felipe commented on src/ACBr.Net.NFSe/Providers/NFSeServiceClient.cs
> +            {
Eu fiz o catch ali pra conseguir colocar breakpoint.

2021-08-26 21:09 UTC, rftd commented on src/ACBr.Net.NFSe/Providers/NFSeServiceClient.cs
> +            {
Não precisa é so coloca um break point onde é feito o catch e ver o stack trace, inner exceptions etc..

2021-08-27 11:57 UTC, Transis-Felipe reviewed
Feito, retirei o catch

2021-08-28 00:03 UTC, rftd approved these changes

2021-08-28 00:03 UTC, merged