Adicionando provedor Equiplano
ACBrNet/ACBr.Net.NFSe pull request #72
Opened 2020-01-23 23:41 UTC by angelomachado

### Considerações

* Cada cidade possui um identificador único do tipo inteiro(IdEntidade)
* A URL de produção e homologação são as mesmas para todas as cidades
* É necessário adicionar ainda o número do emissor Rps(tag nrEmissorRps)
* Permiti que o item da lista de serviços da prefeitura seja adicionado item a item
* Todos os endpoints foram testados na cidade de Toledo, PR. Pretendo testar em outras cidades em breve

2020-01-23 23:56 UTC, rftd reviewed
Em Analise.

2020-01-24 00:02 UTC, rftd requested changes
Falto a modificação no ProviderManager.
Fora isso ficou muito bom o provedor ainda mais quando foge do padrão ABRSAF.
Obrigado pela contribuição.

2020-01-24 00:50 UTC, merged

2020-01-24 01:59 UTC, angelomachado commented
Legal. Não alterei nada na tela de cadastro do município, então para adicionar uma nova cidade talvez seja interessante permitir informar o IdEntidade(int) do município(Toledo PR usa o 136 por ex.). O nrEmissorRps está setado como 1 no xml gerado pelo provider, talvez seja necessário permitir informar também na nota também.

2020-01-24 02:02 UTC, rftd commented
blz vou fazer estes ajustes e já subo.